const banks =[
    { label: 'select bank', value: '' },
    { label: 'Allahabad Bank', value: 'Allahabad Bank' },
    { label: 'Andhra Bank', value: 'Andhra Bank' },
    { label: 'Axis Bank', value: 'Axis Bank' },
    { label: 'Bank Bikaner & Jaipur', value: 'Bank Bikaner & Jaipur' },
    { label: 'Bank of Baroda', value: 'Bank of Baroda' },
    { label: 'Bank of India', value: 'Bank of India' },
    { label: 'Bank of Maharashtra', value: 'Bank of Maharashtra' },
    { label: 'Canara Bank', value: 'Canara Bank' },
    { label: 'Central Bank of India', value: 'Central Bank of India' },
    { label: 'Corporation Bank', value: 'Corporation Bank' },
    { label: 'Dena Bank', value: 'Dena Bank' },
    { label: 'HDFC Bank', value: 'HDFC Bank' },
    { label: 'ICICI Bank', value: 'ICICI Bank' },
    { label: 'IDBI Bank', value: 'IDBI Bank' },
    { label: 'Indian Bank', value: 'Indian Bank' },
    { label: 'Indian Overseas Bank', value: 'Indian Overseas Bank' },
    { label: 'IndusInd Bank', value: 'IndusInd Bank' },
    { label: 'ING Vysya Bank', value: 'ING Vysya Bank' },
    { label: 'Karnataka Bank', value: 'Karnataka Bank' },
    { label: 'Karur Vysya Bank', value: 'Karur Vysya Bank' },
    { label: 'Kotak Mahindra Bank', value: 'Kotak Mahindra Bank' },
    { label: 'Oriental Bank of Commerce', value: 'Oriental Bank of Commerce' },
    { label: 'Punjab & Sind Bank', value: 'Punjab & Sind Bank' },
    { label: 'Punjab National Bank', value: 'Punjab National Bank' },
    { label: 'Saraswat Bank', value: 'Saraswat Bank' },
    { label: 'South Indian Bank', value: 'South Indian Bank' },
    { label: 'State Bank of Hyderabad', value: 'State Bank of Hyderabad' },
    { label: 'State Bank of India', value: 'State Bank of India' },
    { label: 'State Bank of Mysore', value: 'State Bank of Mysore' },
    { label: 'State Bank of Patiala', value: 'State Bank of Patiala' },
    { label: 'State Bank of Travancore', value: 'State Bank of Travancore' },
    { label: 'THE BHARAT CO-OPERATIVE BANK', value: 'THE BHARAT CO-OPERATIVE BANK' },
    { label: 'The Nainital Bank Ltd', value: 'The Nainital Bank Ltd' },
    { label: 'United Bank of India', value: 'United Bank of India' },
    { label: 'Vijaya Bank', value: 'Vijaya Bank' },
    { label: 'Yes Bank', value: 'Yes Bank' },
  ];

  export default banks;